server:
    port: 8084

spring:
  application:
    name: API-GATEWAY

    cloud:
      gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1