server:
  port: 8083

spring:
  application:
    name: QUALIFICATION-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  mongodb:
    uri: mongodb://localhost:27017/msvc
    database: msvc

