server:
  port: 8083

spring:
  mongodb:
    url: mongodb://localhost:27017
    database: microservice

  application:
    name: QUALIFICATION-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka