server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JUTHALEN/microservice-config.server
          clone-on-start: true

